[features]
seeds = false
skip-lint = false
[programs.localnet]
evidence_storage = "8uXuTvhpfLXpdyJ1E8tkFAhHYREMhbSGrFrciX9PgoiA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/aolyang/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
